### PR TITLE
Some tune about jraft.

### PR DESCRIPTION
**Pull request by horizonzy**
For https://github.com/sofastack/sofa-jraft/issues/588

### CODE REVIEW

**Comment by nobodyiam** [comment]
@fengjiachun please help to review

**Comment by fengjiachun** [comment]
中英文之间加一个空格怎么样？

**Comment by horizonzy** [comment]
> 中英文之间加一个空格怎么样？

done.

**Review by fengjiachun — APPROVED** [review]
lgtm

**Review by fengjiachun — APPROVED** [review]

**Review by seeflood — APPROVED** [review]
LGTM

**Pull request merged**
